In [1]:
import numpy as np
import tensorflow as tf
from matplotlib.image import imread
from os import listdir
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
traindata_x = []
traindata_y = []
for file in listdir("deepl_files/data"):
    if file.split(".")[1] == "png":
        traindata_x.append(imread("deepl_files/data/" + file))
        traindata_y.append(file.split("_")[0])

In [3]:
testdata_x = []
testdata_y = []
for file in listdir("deepl_files/data_test"):
    if file.split(".")[1] == "png":
        testdata_x.append(imread("deepl_files/data/" + file))
        testdata_y.append(file.split("_")[0])

In [4]:
traindata_x = [x.flatten() for x in traindata_x]
testdata_x = [x.flatten() for x in testdata_x]

In [5]:
X_train = np.array(traindata_x)
y_train = np.array(traindata_y)
X_test = np.array(testdata_x)
y_test = np.array(testdata_y)

In [6]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
print(y_train)
n_classes = len(np.unique(y_train))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [7]:
encoder = LabelEncoder()
y_test = encoder.fit_transform(y_test)
print(y_test)

[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [8]:
encoder_onehot = OneHotEncoder(sparse=False)
y_train = encoder_onehot.fit_transform(y_train.reshape([-1,1]))
print(y_train)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [9]:
y_test = encoder_onehot.transform(y_test.reshape([-1,1]))
y_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [10]:
n_classes = len(np.unique(traindata_y))
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_shape=[X_train[0].shape[0]], activation="relu"),
    tf.keras.layers.Dense(16, "relu"),
    tf.keras.layers.Dense(n_classes, "softmax")
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                76864     
_________________________________________________________________
dense_1 (Dense)              (None, 16)                1040      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 77,955
Trainable params: 77,955
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(
    loss=tf.keras.losses.CategoricalCrossentropy(),
    optimizer = 'adam',
    metrics=['accuracy']
    )

In [12]:
model.fit(X_train, y_train, epochs=10, verbose=2)

Train on 30 samples
Epoch 1/10
30/30 - 0s - loss: 1.2030 - accuracy: 0.2333
Epoch 2/10
30/30 - 0s - loss: 0.8810 - accuracy: 0.7000
Epoch 3/10
30/30 - 0s - loss: 0.7385 - accuracy: 0.8000
Epoch 4/10
30/30 - 0s - loss: 0.5935 - accuracy: 0.9667
Epoch 5/10
30/30 - 0s - loss: 0.4828 - accuracy: 0.9667
Epoch 6/10
30/30 - 0s - loss: 0.4043 - accuracy: 0.9333
Epoch 7/10
30/30 - 0s - loss: 0.3346 - accuracy: 0.9333
Epoch 8/10
30/30 - 0s - loss: 0.2686 - accuracy: 0.9667
Epoch 9/10
30/30 - 0s - loss: 0.2180 - accuracy: 1.0000
Epoch 10/10
30/30 - 0s - loss: 0.1838 - accuracy: 1.0000


In [13]:
y_pred = model.predict(X_test)

In [14]:
print(encoder.inverse_transform(np.argmax(y_test, axis=1)), "True values")
print(encoder.inverse_transform(np.argmax(y_pred, axis=1)), "Predicted values")

['16' '16' '16' '16' '16' '3' '3' '3' '3' '3' '4' '4' '4' '4' '4'] True values
['16' '16' '16' '16' '16' '3' '3' '3' '3' '3' '4' '4' '4' '4' '4'] Predicted values
